name: 'Test Report'
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            dotnet-arch: 'x64'
          - os: windows-11-arm
            dotnet-arch: 'arm64'
    name: Test - ${{ matrix.dotnet-arch }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Display test results
      uses: dorny/test-reporter@v2
      with:
        artifact: test-results-${{ matrix.dotnet-arch }}
        name: Test - Results - ${{ matrix.dotnet-arch }}
        path: '*.trx'
        reporter: dotnet-trx